import 'app_messages_key.dart';

const Map<String, String> en_us = {
  AppMessagesKey.message: 'Hello world!',
  AppMessagesKey.login: 'Log in',
  AppMessagesKey.loginButtonText: 'Login',
  AppMessagesKey.selectServer: "Select server",
  AppMessagesKey.email: "Email",
  AppMessagesKey.enterEmail: "Enter your email",
  AppMessagesKey.password: "Password",
  AppMessagesKey.enterPassword: "Enter your password",
  AppMessagesKey.forgotPassword: "Forgot Password?",
  AppMessagesKey.or: "OR",
  AppMessagesKey.siginWithGoogle: "Sign in with Google",
  AppMessagesKey.cancel: "Cancel",
  AppMessagesKey.save: "Save",
  AppMessagesKey.resetPassword: "Reset Password",
  AppMessagesKey.enterYourEmailText:
      "Enter your email below to receive password reset instructions",
  AppMessagesKey.sendMeResetCode: "Send me reset code",
  AppMessagesKey.checkYourMail: "Check your mail box",
  AppMessagesKey.weHaveSentEmail:
      "We have sent recover instructions to your email",
  AppMessagesKey.openMail: "Open mail app",
  AppMessagesKey.iWillCheckLater: "I'll check it later",
  AppMessagesKey.enterEmailSMS:
      "Enter your email below to recevie password 2FA Code",
  AppMessagesKey.twoFactorAuthentication: "2 Factor Authentication",
  AppMessagesKey.enterCode: "Enter the code",
  AppMessagesKey.didNotreciveCode: "Didn't recive verification code?",
  AppMessagesKey.resendCode: "Resend code",
  AppMessagesKey.continueText: "Continue",
  AppMessagesKey.updatePassword: "Update Password",
  AppMessagesKey.newPassword: "New Password",
  AppMessagesKey.enterNewPassword: "Enter New Password",
  AppMessagesKey.confirmPassword: "Confirm Password",
  AppMessagesKey.enterConfirmPassword: "Enter Confirm Password",
  AppMessagesKey.newSession: "New Session",
  AppMessagesKey.continueSession: "Continue Session",
  AppMessagesKey.siginWithApple: "Sign in with Apple",
  AppMessagesKey.privacyPolicy: "Privacy policy",
  AppMessagesKey.schedule: "Schedule",
  AppMessagesKey.declined: "Declined",
  AppMessagesKey.next: "Next",
  AppMessagesKey.days: "Days",
  AppMessagesKey.cellPhone: "Cell phone",
  AppMessagesKey.homePhone: "Home phone",
  AppMessagesKey.client: "Client",
  AppMessagesKey.calendar: "Calendar",
  AppMessagesKey.wishlist: "Wishlist",
  AppMessagesKey.myProfile: "My Profile",
  AppMessagesKey.support: "Support",
  AppMessagesKey.logout: "Logout",
  AppMessagesKey.genralInformation: "General Information",
  AppMessagesKey.seniority: "Seniority",
  AppMessagesKey.shiftCount: "Shift Count",
  AppMessagesKey.street: "Street",
  AppMessagesKey.pObox: "P.O. Box",
  AppMessagesKey.primaryEmail: "Primary Email",
  AppMessagesKey.secondaryEmail: "Secondary Email",
  AppMessagesKey.memberSince: "Member Since",
  AppMessagesKey.dateOfHire: "Date of Hire",
  AppMessagesKey.status: "Status",
  AppMessagesKey.locals: "Locals",
  AppMessagesKey.skillSet: "Skill set",
  AppMessagesKey.editProfile: "Edit Profile",
  AppMessagesKey.camera: "Camera",
  AppMessagesKey.gallery: "Gallery",
  AppMessagesKey.changeProfileImage: "Change Profile Image",
  AppMessagesKey.uploadFromPhone: "Upload from phone",
  AppMessagesKey.firstName: "First Name",
  AppMessagesKey.lastName: "Last Name",
  AppMessagesKey.nickName: "Nick Name",
  AppMessagesKey.streetAddress: "Street Address",
  AppMessagesKey.city: "City",
  AppMessagesKey.state: "State",
  AppMessagesKey.zip: "Zip",
  AppMessagesKey.country: "Country",
  AppMessagesKey.selectCountry: "Select Country",
  AppMessagesKey.back: "Back",
  AppMessagesKey.requiredField: "**REQUIRED FIELD**",
  AppMessagesKey.removeAllSpaceText: "** Remove ALL Spaces,Dots,Dashes **",
  AppMessagesKey.onlyDigitText:
      "REQUIRED, 10 - 12 digits- Exclude all Dots, Spaces and Dashes.",
  AppMessagesKey.authority: "Authority",
  AppMessagesKey.youdonthave:
      "You don't have permission to Locked and Unlocked Skills",
  AppMessagesKey.locked: "Locked",
  AppMessagesKey.unlocked: "Unlocked",
  AppMessagesKey.action: "Action",
  AppMessagesKey.all: "All",
  AppMessagesKey.none: "None",
  AppMessagesKey.vacation: "Vacation",
  AppMessagesKey.policy: "Policy",
  AppMessagesKey.addVacation: "Add Vacation",
  AppMessagesKey.running: "Running",
  AppMessagesKey.currentlyAvailable: "Currently Available",
  AppMessagesKey.onLeaveFrom: "On Leave From",
  AppMessagesKey.to: "to",
  AppMessagesKey.upcoming: "Upcoming",
  AppMessagesKey.noUpcomingLeavefound: "No Upcoming Leave found",
  AppMessagesKey.viewHistory: "View History",
  AppMessagesKey.vacationHistory: "Vacation History",
  AppMessagesKey.availability: "Unavailability",
  AppMessagesKey.recurringAvailability: "Recurring Unavailability",
  AppMessagesKey.enterStart:
      "Enter the start and end times of unavailable periods separated by a hyphen (ex: 1:00-18:00 ). ). For multiple periods within a single day, separate periods with a comma (ex: 1:00-18:30,20:30-22:30)",
  AppMessagesKey.occupiedFrom: "Occupied From",
  AppMessagesKey.available: "Available",
  AppMessagesKey.requestTimeOff: "Request Time off:",
  AppMessagesKey.label: "Label",
  AppMessagesKey.textArea: "Text area",
  AppMessagesKey.startDate: "Start Date",
  AppMessagesKey.startTime: "Start Time",
  AppMessagesKey.endTime: "End Time",
  AppMessagesKey.endDate: "End Date",
  AppMessagesKey.submit: "Submit",
  AppMessagesKey.warning: "Warning",
  AppMessagesKey.thisWillDelete:
      "This will permanently delete the file. Continue?",
  AppMessagesKey.ok: "OK",
  AppMessagesKey.editVacation: "Edit Vacation",
  AppMessagesKey.contactYourDispatcher:
      "Contact your Dispatcher! Booking Conflict -",
  AppMessagesKey.tookLeaveFrom: "Took leave from",
  AppMessagesKey.notifyAndActionLog: "Notify and Action Log",
  AppMessagesKey.notifyLog: "Notify Log",
  AppMessagesKey.actionLog: "Action Log",
  AppMessagesKey.timestamp: "Timestamp",
  AppMessagesKey.jobID: "Job ID",
  AppMessagesKey.initiator: "Initiator",
  AppMessagesKey.type: "Type",
  AppMessagesKey.content: "Content",
  AppMessagesKey.serverResponse: "Server Response",
  AppMessagesKey.affectedUser: "Affected User",
  AppMessagesKey.position: "Position",
  AppMessagesKey.callstart: "Call start",
  AppMessagesKey.callend: "Call end",
  AppMessagesKey.event: "Event",
  AppMessagesKey.settings: "Settings",
  AppMessagesKey.formatting: "Formatting",
  AppMessagesKey.dateFormat: "Date Format",
  AppMessagesKey.timeFormat: "Time Format",
  AppMessagesKey.notifications: "Notifications",
  AppMessagesKey.selectWhichChannel:
      "Select which channel you want to notified at",
  AppMessagesKey.app: "App",
  AppMessagesKey.emailPrimary: "Email (primary)",
  AppMessagesKey.sms: "SMS (cell)",
  AppMessagesKey.stopEmailAndSMS: "Stop Email and SMS",
  AppMessagesKey.receive: "Receive",
  AppMessagesKey.stop: "STOP",
  AppMessagesKey.announcementsFrom: "Announcements from other IATSE Locals",
  AppMessagesKey.anEmailList: "An Email List",
  AppMessagesKey.changeLocal: "Change Local",
  AppMessagesKey.changeLanguage: "Change Language",
  AppMessagesKey.areYousure: "Are you sure you want to logout?",
  AppMessagesKey.pleaseStandBy:
      "Please Stand By \n We are looking for your next job \n Check Back Soon",
  AppMessagesKey.job: "Job",
  AppMessagesKey.venue: "Venue",
  AppMessagesKey.rateHr: "Rate/hr",
  AppMessagesKey.confirm: "Confirm",
  AppMessagesKey.pass: "Pass",
  AppMessagesKey.decline: "Decline",
  AppMessagesKey.confirmCall:
      "Are you sure you would like to Confirm this Call?",
  AppMessagesKey.muaConflict:
      "This call conflicts with a previous confirmation. Accepting this call will automatically clear the previous confirmation ! Contact your dispatcher first !",
  AppMessagesKey.passCall: "Are you sure you would like to pass this Call?",
  AppMessagesKey.declineCall:
      "Are you sure you would like to decline this Call? You are about to remove yourself from availability for 24 hours on",
  AppMessagesKey.call: "Call",
  AppMessagesKey.jobSteward: "Job Steward",
  AppMessagesKey.jobVenue: "Job Venue",
  AppMessagesKey.contact: "Contact",
  AppMessagesKey.callNote: "Call Note",
  AppMessagesKey.comments: "Comments",
  AppMessagesKey.employer: "Employer",
  AppMessagesKey.employerContact: "Employer Contact",
  AppMessagesKey.employerRequests: "Employer Requests",
  AppMessagesKey.findCarpool: "Find Carpool",
  AppMessagesKey.location: "Location",
  AppMessagesKey.notice: "Notice",
  AppMessagesKey.report: "Report",
  AppMessagesKey.date: "Date",
  AppMessagesKey.hW: "HW",
  AppMessagesKey.jobCalls: "Job Calls",
  AppMessagesKey.yes: "Yes",
  AppMessagesKey.no: "No",
  AppMessagesKey.enterAvailability: "Enter availability",
  AppMessagesKey.jobDetails: "Job Details",
  AppMessagesKey.wished: "Wished",
  AppMessagesKey.ignored: "Ignored",
  AppMessagesKey.dispatchedBy: "Dispatched by",
  AppMessagesKey.payroll: "Payroll",
  AppMessagesKey.viewCall: "View Call",
  AppMessagesKey.dailyStandby: "Daily Standby",
  AppMessagesKey.dailyStandbyDescriprion:
      "Check this switch to make yourself available for today and your dispatcher will be updated. This switch will be updated every day, 10pm local.",
  AppMessagesKey.wishlistInstructions:
      "To move a Scheduled jobs to either the Wished or Ignored jobs list,  perform a long press on the job and drag it to the desired category. Don't forget to leave a note for dispatch.",
  AppMessagesKey.scheduledJob: "Scheduled Jobs",
  AppMessagesKey.wishedJob: "Wished Jobs",
  AppMessagesKey.ignoredJob: "Ignored Jobs",
  AppMessagesKey.notesForDispatcher: "Notes For Dispatcher",
  AppMessagesKey.dateRange: "Date Range",
  AppMessagesKey.eventName: "Event name",
  AppMessagesKey.steward: "Steward",
  AppMessagesKey.tokenExpired:
      "Your session has expired. please log in to continue",
};
