import 'app_messages_key.dart';

const Map<String, String> es_ES = {
  AppMessagesKey.message: '¡Hola Mundo!',
  AppMessagesKey.login: 'iniciar sesión',
  AppMessagesKey.loginButtonText: 'Acceso',
  AppMessagesKey.selectServer: "Seleccionar servidor",
  AppMessagesKey.email: "Correo electrónico",
  AppMessagesKey.enterEmail: "Introduce tu correo electrónico",
  AppMessagesKey.password: "Contraseña",
  AppMessagesKey.enterPassword: "Ingresa tu contraseña",
  AppMessagesKey.forgotPassword: "¿Has olvidado tu contraseña?",
  AppMessagesKey.or: "o",
  AppMessagesKey.siginWithGoogle: "Inicia sesión con Google",
  AppMessagesKey.cancel: "Cancelar",
  AppMessagesKey.save: "Guardar",
  AppMessagesKey.resetPassword: "Restablecer la contraseña",
  AppMessagesKey.enterYourEmailText:
      "Ingrese su correo electrónico a continuación para recibir instrucciones para restablecer la contraseña",
  AppMessagesKey.sendMeResetCode: "Envíame el código de reinicio",
  AppMessagesKey.checkYourMail: "Revisa tu correo",
  AppMessagesKey.weHaveSentEmail:
      "Hemos enviado instrucciones de recuperación a su correo electrónico.",
  AppMessagesKey.openMail: "Abrir aplicación de correo",
  AppMessagesKey.iWillCheckLater: "Lo comprobaré más tarde",
  AppMessagesKey.enterEmailSMS:
      "Ingrese su correo electrónico a continuación para recibir la contraseña Código 2FA",
  AppMessagesKey.twoFactorAuthentication: "Autenticación de 2 factores",
  AppMessagesKey.enterCode: "Ingrese el código",
  AppMessagesKey.didNotreciveCode: "¿No recibiste el código de verificación?",
  AppMessagesKey.resendCode: "Reenviar codigo",
  AppMessagesKey.continueText: "Continuar",
  AppMessagesKey.updatePassword: "Actualiza contraseña",
  AppMessagesKey.newPassword: "Nueva contraseña",
  AppMessagesKey.enterNewPassword: "Ingrese nueva clave",
  AppMessagesKey.confirmPassword: "confirmar Contraseña",
  AppMessagesKey.enterConfirmPassword: "Ingresar Confirmar contraseña",
  AppMessagesKey.newSession: "Nueva sesión",
  AppMessagesKey.continueSession: "Continuar Sesión",
  AppMessagesKey.siginWithApple: "Iniciar sesión con Apple",
  AppMessagesKey.privacyPolicy: "Política de privacidad",
  AppMessagesKey.schedule: "Cronograma",
  AppMessagesKey.declined: "Rechazado",
  AppMessagesKey.next: "Próximo",
  AppMessagesKey.days: "días",
  AppMessagesKey.cellPhone: "Teléfono móvil",
  AppMessagesKey.homePhone: "Teléfono de casa",
  AppMessagesKey.client: "Cliente",
  AppMessagesKey.calendar: "Calendario",
  AppMessagesKey.wishlist: "Lista de deseos",
  AppMessagesKey.myProfile: "Mi perfil",
  AppMessagesKey.support: "Apoyo",
  AppMessagesKey.logout: "Cerrar sesión",
  AppMessagesKey.genralInformation: "Información general",
  AppMessagesKey.seniority: "Antigüedad",
  AppMessagesKey.shiftCount: "Recuento de turnos",
  AppMessagesKey.street: "Calle",
  AppMessagesKey.pObox: "CORREOS. Caja",
  AppMessagesKey.primaryEmail: "Correo electrónico principal",
  AppMessagesKey.secondaryEmail: "Email secundario",
  AppMessagesKey.memberSince: "Miembro desde",
  AppMessagesKey.dateOfHire: "Fecha de contratación",
  AppMessagesKey.status: "Estado",
  AppMessagesKey.locals: "Locales",
  AppMessagesKey.skillSet: "Conjunto de habilidades",
  AppMessagesKey.editProfile: "Editar perfil",
  AppMessagesKey.camera: "Cámara",
  AppMessagesKey.gallery: "Galería",
  AppMessagesKey.changeProfileImage: "Cambiar imagen de perfil",
  AppMessagesKey.uploadFromPhone: "Subir desde el teléfono",
  AppMessagesKey.firstName: "Nombre de pila",
  AppMessagesKey.lastName: "Apellido",
  AppMessagesKey.nickName: "Apodo",
  AppMessagesKey.streetAddress: "Dirección",
  AppMessagesKey.city: "Ciudad",
  AppMessagesKey.state: "Estado",
  AppMessagesKey.zip: "Cremallera",
  AppMessagesKey.country: "Código Postal",
  AppMessagesKey.selectCountry: "Seleccionar país",
  AppMessagesKey.back: "atrás",
  AppMessagesKey.requiredField: "**CAMPO REQUERIDO**",
  AppMessagesKey.removeAllSpaceText:
      "** Eliminar TODOS los espacios, puntos, guiones **",
  AppMessagesKey.onlyDigitText:
      "OBLIGATORIO, 10 - 12 dígitos: excluye todos los puntos, espacios y guiones.",
  AppMessagesKey.authority: "Autoridad",
  AppMessagesKey.youdonthave:
      "No tienes permiso para las habilidades bloqueadas y desbloqueadas",
  AppMessagesKey.locked: "Bloqueado",
  AppMessagesKey.unlocked: "Desbloqueado",
  AppMessagesKey.action: "Acción",
  AppMessagesKey.all: "Toda",
  AppMessagesKey.none: "Ninguna",
  AppMessagesKey.vacation: "Vacaciones",
  AppMessagesKey.policy: "Política",
  AppMessagesKey.addVacation: "Agregar vacaciones",
  AppMessagesKey.running: "Correr",
  AppMessagesKey.currentlyAvailable: "Actualmente disponible",
  AppMessagesKey.onLeaveFrom: "Con permiso de",
  AppMessagesKey.to: "a",
  AppMessagesKey.upcoming: "Próxima",
  AppMessagesKey.noUpcomingLeavefound: "No se encontraron vacaciones próximas",
  AppMessagesKey.viewHistory: "Ver historial",
  AppMessagesKey.vacationHistory: "Historial de vacaciones",
  AppMessagesKey.availability: "Indisponibilidad",
  AppMessagesKey.recurringAvailability: "Indisponibilidad recurrente",
  AppMessagesKey.enterStart:
      "Ingrese las horas de inicio y finalización de los períodos no disponibles separados por un guión (por ejemplo, 1:00-18:00). ). Para períodos múltiples dentro de un solo día, separe los períodos con una coma (por ejemplo: 1:00-18:30, 20:30-22:30)",
  AppMessagesKey.occupiedFrom: "Ocupado desde",
  AppMessagesKey.available: "Disponible",
  AppMessagesKey.requestTimeOff: "Solicitar tiempo libre:",
  AppMessagesKey.label: "Etiqueta",
  AppMessagesKey.textArea: "área de texto",
  AppMessagesKey.startDate: "Fecha de inicio",
  AppMessagesKey.startTime: "Hora de inicio",
  AppMessagesKey.endTime: "Hora de finalización",
  AppMessagesKey.endDate: "Fecha final",
  AppMessagesKey.submit: "Entregar",
  AppMessagesKey.warning: "Advertencia",
  AppMessagesKey.thisWillDelete:
      "Esto eliminará permanentemente el archivo. ¿Continuar?",
  AppMessagesKey.ok: "DE ACUERDO",
  AppMessagesKey.editVacation: "Editar vacaciones",
  AppMessagesKey.contactYourDispatcher:
      "¡Contacta a tu Despachador! Conflicto de reserva -",
  AppMessagesKey.tookLeaveFrom: "se despidió de",
  AppMessagesKey.notifyAndActionLog: "Notificar y registro de acciones",
  AppMessagesKey.notifyLog: "Notificar registro",
  AppMessagesKey.actionLog: "Registro de Acción",
  AppMessagesKey.timestamp: "marca de tiempo",
  AppMessagesKey.jobID: "Identificación del trabajo",
  AppMessagesKey.initiator: "Iniciadora",
  AppMessagesKey.type: "Tipo",
  AppMessagesKey.content: "ContentContenido",
  AppMessagesKey.serverResponse: "Respuesta del servidor",
  AppMessagesKey.affectedUser: "Usuario afectada",
  AppMessagesKey.position: "Posición",
  AppMessagesKey.callstart: "inicio de llamada",
  AppMessagesKey.callend: "Fin de llamada",
  AppMessagesKey.event: "Evento",
  AppMessagesKey.settings: "Ajustes",
  AppMessagesKey.formatting: "Formateo",
  AppMessagesKey.dateFormat: "Formato de fecha",
  AppMessagesKey.timeFormat: "Formato de tiempo",
  AppMessagesKey.notifications: "Notificaciones",
  AppMessagesKey.selectWhichChannel:
      "Seleccione en qué canal desea recibir notificaciones",
  AppMessagesKey.app: "aplicación",
  AppMessagesKey.emailPrimary: "Correo electrónico (principal)",
  AppMessagesKey.sms: "SMS (celular)",
  AppMessagesKey.stopEmailAndSMS: "Detener correo electrónico y SMS",
  AppMessagesKey.receive: "Recibir",
  AppMessagesKey.stop: "DETENER",
  AppMessagesKey.announcementsFrom: "Anuncios de otros locales de IATSE",
  AppMessagesKey.anEmailList: "Una lista de correo electrónico",
  AppMessagesKey.changeLocal: "Cambiar local",
  AppMessagesKey.changeLanguage: "Cambiar idioma",
  AppMessagesKey.areYousure: "¿Estás segura de que quieres cerrar sesión?",
  AppMessagesKey.pleaseStandBy:
      "Espere \n Estamos buscando su próximo trabajo \n Vuelva pronto",
  AppMessagesKey.job: "Trabajo",
  AppMessagesKey.venue: "Evento",
  AppMessagesKey.rateHr: "Tasa/hora",
  AppMessagesKey.confirm: "Confirmar",
  AppMessagesKey.pass: "Aprobar",
  AppMessagesKey.decline: "Rechazar",
  AppMessagesKey.confirmCall:
      "¿Está seguro de que desea confirmar esta llamada?",
  AppMessagesKey.muaConflict:
      "Esta llamada entra en conflicto con una confirmación anterior. ¡Aceptar esta llamada borrará automáticamente la confirmación anterior! ¡Póngase en contacto con su despachador primero!",
  AppMessagesKey.passCall:
      "¿Estás seguro de que te gustaría pasar esta Convocatoria?",
  AppMessagesKey.declineCall:
      "¿Está seguro de que desea rechazar esta llamada? Está a punto de dejar de estar disponible durante 24 horas el",
  AppMessagesKey.call: "Llamar",
  AppMessagesKey.jobSteward: "administrador de trabajo",
  AppMessagesKey.jobVenue: "lugar de trabajo",
  AppMessagesKey.contact: "Contacto",
  AppMessagesKey.callNote: "Nota de llamada",
  AppMessagesKey.comments: "Comentarios",
  AppMessagesKey.employer: "Empleadora",
  AppMessagesKey.employerContact: "Contacto del empleador",
  AppMessagesKey.employerRequests: "Solicitudes del empleador",
  AppMessagesKey.findCarpool: "Buscar viaje compartido",
  AppMessagesKey.location: "Ubicación",
  AppMessagesKey.notice: "Aviso",
  AppMessagesKey.report: "Informe",
  AppMessagesKey.date: "Fecha",
  AppMessagesKey.hW: "HW",
  AppMessagesKey.jobCalls: "Llamadas de trabajo",
  AppMessagesKey.yes: "Sí",
  AppMessagesKey.no: "No",
  AppMessagesKey.enterAvailability: "Introducir disponibilidad",
  AppMessagesKey.jobDetails: "Detalles del trabajo",
  AppMessagesKey.wished: "Deseada",
  AppMessagesKey.ignored: "Ignorada",
  AppMessagesKey.notesForDispatcher: "Notas para el despachador",
  AppMessagesKey.dispatchedBy: "Enviado por",
  AppMessagesKey.payroll: "Nómina de sueldos",
  AppMessagesKey.viewCall: "Ver llamada",
  AppMessagesKey.dailyStandby: "Daily Standby",
  AppMessagesKey.dailyStandbyDescriprion:
      "Cochez cette option pour vous rendre disponible pour aujourd'hui et votre répartiteur sera mis à jour. Ce commutateur sera mis à jour tous les jours, à 22h00 locales.",
  AppMessagesKey.wishlistInstructions:
      "Para mover un trabajo programado a la lista de trabajos deseados o ignorados, mantenga presionado el trabajo y arrástrelo a la categoría deseada. No olvides dejar una nota para el envío.",
  AppMessagesKey.scheduledJob: "Tâches planifiées",
  AppMessagesKey.wishedJob: "Emplois souhaités",
  AppMessagesKey.ignoredJob: "Tâches ignorées",
  AppMessagesKey.dateRange: "Plage de dates",
  AppMessagesKey.eventName: "Nom de l'événement",
  AppMessagesKey.steward: "Mayordomo",
  AppMessagesKey.tokenExpired:
      "Su sesión ha caducado. Por favor inicie sesión para continuar",
};
