import 'app_messages_key.dart';

const Map<String, String> fr_CA = {
  AppMessagesKey.message: 'Bonjour le monde!',
  AppMessagesKey.login: 'Connexion',
  AppMessagesKey.loginButtonText: 'Connexion',
  AppMessagesKey.selectServer: "Sélectionnez le serveur",
  AppMessagesKey.email: "E-mail",
  AppMessagesKey.enterEmail: "Entrer votre Email",
  AppMessagesKey.password: "Mot de passe",
  AppMessagesKey.enterPassword: "Tapez votre mot de passe",
  AppMessagesKey.forgotPassword: "Mot de passe oublié?",
  AppMessagesKey.or: "OU ALORS",
  AppMessagesKey.siginWithGoogle: "Connectez-vous avec Google",
  AppMessagesKey.cancel: "Annuler",
  AppMessagesKey.save: "Sauver",
  AppMessagesKey.resetPassword: "réinitialiser le mot de passe",
  AppMessagesKey.enterYourEmailText:
      "Entrez votre e-mail ci-dessous pour recevoir les instructions de réinitialisation du mot de passe",
  AppMessagesKey.sendMeResetCode: "Envoyez-moi le code de réinitialisation",
  AppMessagesKey.checkYourMail: "Vérifiez votre boîte mail",
  AppMessagesKey.weHaveSentEmail:
      "Nous avons envoyé des instructions de récupération à votre adresse e-mail",
  AppMessagesKey.openMail: "Ouvrir l'application de messagerie",
  AppMessagesKey.iWillCheckLater: "je vérifierai plus tard",
  AppMessagesKey.enterEmailSMS:
      "Entrez votre email ci-dessous pour recevoir le mot de passe 2FA Code",
  AppMessagesKey.twoFactorAuthentication: "Authentification à 2 facteurs",
  AppMessagesKey.enterCode: "Entrer le code",
  AppMessagesKey.didNotreciveCode:
      "Vous n'avez pas reçu le code de vérification?",
  AppMessagesKey.resendCode: "Renvoyer le code",
  AppMessagesKey.continueText: "Continuer",
  AppMessagesKey.updatePassword: "Mettre à jour le mot de passe",
  AppMessagesKey.newPassword: "nouveau mot de passe",
  AppMessagesKey.enterNewPassword: "Entrez un nouveau mot de passe",
  AppMessagesKey.confirmPassword: "Confirmez le mot de passe",
  AppMessagesKey.enterConfirmPassword: "Entrez Confirmer le mot de passe",
  AppMessagesKey.newSession: "Nouvelle séance",
  AppMessagesKey.continueSession: "Continuer la session",
  AppMessagesKey.siginWithApple: "Connectez-vous avec Apple",
  AppMessagesKey.privacyPolicy: "Politique de confidentialité",
  AppMessagesKey.schedule: "Calendrier",
  AppMessagesKey.declined: "Diminué",
  AppMessagesKey.next: "Suivant",
  AppMessagesKey.cellPhone: "Téléphone portable",
  AppMessagesKey.days: "jours",
  AppMessagesKey.homePhone: "Téléphone fixe",
  AppMessagesKey.client: "Cliente",
  AppMessagesKey.calendar: "Calendrier",
  AppMessagesKey.wishlist: "Liste de souhaits",
  AppMessagesKey.myProfile: "Mon profil",
  AppMessagesKey.support: "Soutien",
  AppMessagesKey.logout: "Se déconnecter",
  AppMessagesKey.genralInformation: "Informations générales",
  AppMessagesKey.seniority: "Ancienneté",
  AppMessagesKey.shiftCount: "Nombre de quarts",
  AppMessagesKey.street: "Rue",
  AppMessagesKey.pObox: "P.O. Boîte",
  AppMessagesKey.primaryEmail: "E-mail principal",
  AppMessagesKey.secondaryEmail: "Email secondaire",
  AppMessagesKey.memberSince: "Membre depuis",
  AppMessagesKey.dateOfHire: "Date d'embauche",
  AppMessagesKey.status: "Statut",
  AppMessagesKey.locals: "des locaux",
  AppMessagesKey.skillSet: "Ensemble de compétences",
  AppMessagesKey.editProfile: "Editer le profil",
  AppMessagesKey.camera: "Caméra",
  AppMessagesKey.gallery: "Galerie",
  AppMessagesKey.changeProfileImage: "Changer l'image du profil",
  AppMessagesKey.uploadFromPhone: "Télécharger depuis le téléphone",
  AppMessagesKey.firstName: "Prénom",
  AppMessagesKey.lastName: "Nom de famille",
  AppMessagesKey.nickName: "Surnom",
  AppMessagesKey.streetAddress: "Adresse de la rue",
  AppMessagesKey.city: "Ville",
  AppMessagesKey.state: "État",
  AppMessagesKey.zip: "Code postal",
  AppMessagesKey.country: "Pays",
  AppMessagesKey.selectCountry: "Choisissez le pays",
  AppMessagesKey.back: "dos",
  AppMessagesKey.requiredField: "**CHAMPS REQUIS**",
  AppMessagesKey.removeAllSpaceText:
      "** Supprimer TOUS les espaces, points, tirets **",
  AppMessagesKey.onlyDigitText:
      "OBLIGATOIRE, 10 à 12 chiffres - Exclure tous les points, espaces et tirets.",
  AppMessagesKey.authority: "Autorité",
  AppMessagesKey.youdonthave:
      "Vous n'êtes pas autorisé à accéder aux compétences verrouillées et déverrouillées",
  AppMessagesKey.locked: "Fermé à clé",
  AppMessagesKey.unlocked: "Débloqué",
  AppMessagesKey.action: "Action",
  AppMessagesKey.all: "Toute",
  AppMessagesKey.none: "Aucune",
  AppMessagesKey.vacation: "vacances",
  AppMessagesKey.policy: "Politique",
  AppMessagesKey.addVacation: "Ajouter des vacances",
  AppMessagesKey.running: "En cours",
  AppMessagesKey.currentlyAvailable: "Actuellement disponible",
  AppMessagesKey.onLeaveFrom: "En congé de",
  AppMessagesKey.to: "pour",
  AppMessagesKey.upcoming: "A venir",
  AppMessagesKey.noUpcomingLeavefound: "Aucun congé à venir trouvé",
  AppMessagesKey.viewHistory: "Voir l'historique",
  AppMessagesKey.vacationHistory: "Historique des vacances",
  AppMessagesKey.availability: "Indisponibilité",
  AppMessagesKey.recurringAvailability: "Indisponibilité récurrente",
  AppMessagesKey.enterStart:
      "Entrez les heures de début et de fin des périodes d'indisponibilité séparées par un trait d'union (ex : 1:00-18:00 ). ). Pour plusieurs périodes au cours d'une même journée, séparez les périodes par une virgule (ex : 1:00-18:30, 20:30-22:30)",
  AppMessagesKey.occupiedFrom: "Occupé depuis",
  AppMessagesKey.available: "Disponible",
  AppMessagesKey.requestTimeOff: "Request Time off:",
  AppMessagesKey.label: "Étiqueter",
  AppMessagesKey.textArea: "Zone de texte",
  AppMessagesKey.startDate: "Date de début",
  AppMessagesKey.startTime: "Heure de début",
  AppMessagesKey.endTime: "Heure de fin",
  AppMessagesKey.endDate: "Date de fin",
  AppMessagesKey.submit: "Soumettre",
  AppMessagesKey.warning: "Avertissement",
  AppMessagesKey.thisWillDelete:
      "Cela supprimera définitivement le fichier. Continuer?",
  AppMessagesKey.ok: "D'ACCORD",
  AppMessagesKey.editVacation: "Modifier les vacances",
  AppMessagesKey.contactYourDispatcher:
      "Contactez votre répartiteur ! Conflit de réservation -",
  AppMessagesKey.tookLeaveFrom: "A pris congé de",
  AppMessagesKey.notifyAndActionLog: "Journal des notifications et des actions",
  AppMessagesKey.notifyLog: "Notifier le journal",
  AppMessagesKey.actionLog: "Journal des actions",
  AppMessagesKey.timestamp: "Horodatage",
  AppMessagesKey.jobID: "ID de tâche",
  AppMessagesKey.initiator: "Initiateur",
  AppMessagesKey.type: "Taper",
  AppMessagesKey.content: "Contenu",
  AppMessagesKey.serverResponse: "Réponse du serveur",
  AppMessagesKey.affectedUser: "Utilisateur concerné",
  AppMessagesKey.position: "Position",
  AppMessagesKey.callstart: "Début d'appel",
  AppMessagesKey.callend: "Fin d'appel",
  AppMessagesKey.event: "Événement",
  AppMessagesKey.settings: "Paramètres",
  AppMessagesKey.formatting: "Mise en page",
  AppMessagesKey.dateFormat: "Format de date",
  AppMessagesKey.timeFormat: "Format de l'heure",
  AppMessagesKey.notifications: "Avis",
  AppMessagesKey.selectWhichChannel:
      "Sélectionnez la chaîne sur laquelle vous souhaitez être averti",
  AppMessagesKey.app: "Application",
  AppMessagesKey.emailPrimary: "Courriel (principal)",
  AppMessagesKey.sms: "SMS (portable)",
  AppMessagesKey.stopEmailAndSMS: "Arrêter les e-mails et SMS",
  AppMessagesKey.receive: "Recevoir",
  AppMessagesKey.stop: "ARRÊT",
  AppMessagesKey.announcementsFrom:
      "Annonces d'autres sections locales de l'IATSE",
  AppMessagesKey.anEmailList: "Une liste de diffusion",
  AppMessagesKey.changeLocal: "Changer de local",
  AppMessagesKey.changeLanguage: "Changer de langue",
  AppMessagesKey.areYousure: "Êtes-vous sûr de vouloir vous déconnecter?",
  AppMessagesKey.pleaseStandBy:
      "Veuillez patienter \n Nous recherchons votre prochain emploi \n Revenez bientôt",
  AppMessagesKey.job: "Emploi",
  AppMessagesKey.venue: "Lieu",
  AppMessagesKey.rateHr: "Tarif/h",
  AppMessagesKey.confirm: "Confirmer",
  AppMessagesKey.pass: "Passer",
  AppMessagesKey.decline: "Déclin",
  AppMessagesKey.confirmCall: "Voulez-vous vraiment confirmer cet appel ?",
  AppMessagesKey.muaConflict:
      "Cet appel est en conflit avec une confirmation précédente. Accepter cet appel effacera automatiquement la confirmation précédente ! Contactez d'abord votre répartiteur !",
  AppMessagesKey.passCall: "Êtes-vous sûr de vouloir passer cet appel ?",
  AppMessagesKey.declineCall:
      "Voulez-vous vraiment refuser cet appel ? Vous êtes sur le point de vous retirer de la disponibilité pendant 24 heures sur",
  AppMessagesKey.call: "Appel",
  AppMessagesKey.jobSteward: "délégué syndical",
  AppMessagesKey.jobVenue: "lieu de travail",
  AppMessagesKey.contact: "Contact",
  AppMessagesKey.callNote: "Note d'appel",
  AppMessagesKey.comments: "commentaires",
  AppMessagesKey.employer: "Employeuse",
  AppMessagesKey.employerContact: "Employer Contact",
  AppMessagesKey.employerRequests: "Demandes de l'employeur",
  AppMessagesKey.findCarpool: "Trouver un covoiturage",
  AppMessagesKey.location: "Emplacement",
  AppMessagesKey.notice: "Avis",
  AppMessagesKey.report: "Rapport",
  AppMessagesKey.date: "Date",
  AppMessagesKey.hW: "HW",
  AppMessagesKey.jobCalls: "Appels d'emploi",
  AppMessagesKey.yes: "Oui",
  AppMessagesKey.no: "Non",
  AppMessagesKey.enterAvailability: "Entrez la disponibilité",
  AppMessagesKey.jobDetails: "Détails du poste",
  AppMessagesKey.wished: "souhaité",
  AppMessagesKey.ignored: "Ignorée",
  AppMessagesKey.dispatchedBy: "Expédié par",
  AppMessagesKey.payroll: "Paie",
  AppMessagesKey.viewCall: "Afficher l'appel",
  AppMessagesKey.dailyStandby: "Veille quotidienne",
  AppMessagesKey.dailyStandbyDescriprion:
      "Cochez cette option pour vous rendre disponible pour aujourd'hui et votre répartiteur sera mis à jour. Ce commutateur sera mis à jour tous les jours, à 22h00 locales.",
  AppMessagesKey.wishlistInstructions:
      "Pour déplacer une tâche planifiée vers la liste des tâches souhaitées ou ignorées, appuyez longuement sur la tâche et faites-la glisser vers la catégorie souhaitée. N'oubliez pas de laisser une note pour l'expédition.",
  AppMessagesKey.scheduledJob: "Tâches planifiées",
  AppMessagesKey.wishedJob: "Emplois souhaités",
  AppMessagesKey.ignoredJob: "Tâches ignorées",
  AppMessagesKey.notesForDispatcher: "Notes pour le répartiteur",
  AppMessagesKey.dateRange: "Plage de dates",
  AppMessagesKey.eventName: "Nom de l'événement",
  AppMessagesKey.steward: "Intendant",
  AppMessagesKey.tokenExpired:
      "Votre session a expiré. Merci de vous connecter pour continuer",
};
