class EditProfileModel {
  EditProfileModel({
    required this.clientId,
    required this.displayName,
    required this.firstName,
    required this.lastName,
    required this.email,
    required this.secondaryEmail,
    required this.driversLicense,
    required this.socialSecurity,
    required this.dob,
    required this.mothersMaidenName,
    required this.totalShifts,
    required this.memberSince,
    required this.dateOfHire,
    required this.sreetAddress,
    required this.sreetCity,
    required this.streetState,
    required this.streetPostcode,
    required this.streetCountry,
    required this.poBoxAddress,
    required this.poBoxCity,
    required this.poBoxState,
    required this.poBoxPostcode,
    required this.poBoxCountry,
    required this.homePhone,
    required this.cellPhone,
    required this.contactName,
    required this.contactNumber,
    required this.medicalConditionsNote,
    required this.regularMedications,
    required this.homePhoneNo,
    required this.cellPhoneNo,
    required this.emergencyEmail,
    required this.skills,
    required this.skillLock,
    required this.employeeStatusId,
    required this.vacationStart,
    required this.vacationEnd,
    required this.image,
    required this.availableTimes,
    required this.seniority,
    required this.customField1,
    required this.customField2,
  });

  String? clientId;
  String? displayName;
  String? firstName;
  String? lastName;
  String? email;
  String? secondaryEmail;
  String? driversLicense;
  String? socialSecurity;
  String? dob;
  String? mothersMaidenName;
  int? totalShifts;
  String? memberSince;
  String? dateOfHire;
  String? sreetAddress;
  String? sreetCity;
  String? streetState;
  String? streetPostcode;
  String? streetCountry;
  String? poBoxAddress;
  String? poBoxCity;
  String? poBoxState;
  String? poBoxPostcode;
  String? poBoxCountry;
  String? homePhone;
  int? cellPhone;
  String? contactName;
  String? contactNumber;
  String? medicalConditionsNote;
  String? regularMedications;
  String? homePhoneNo;
  String? cellPhoneNo;
  String? emergencyEmail;
  String? skills;
  int? skillLock;
  String? employeeStatusId;
  String? vacationStart;
  String? vacationEnd;
  String? image;
  String? availableTimes;
  String? seniority;
  String? customField1;
  String? customField2;

  Map<String, dynamic> toJson() => {
        "client_id": clientId,
        "display_name": displayName,
        "first_name": firstName,
        "last_name": lastName,
        "email": email,
        "secondary_email": secondaryEmail,
        "drivers_license": driversLicense,
        "social_security": socialSecurity,
        "dob": dob,
        "mothers_maiden_name": mothersMaidenName,
        "total_shifts": totalShifts,
        "member_since": memberSince,
        "date_of_hire": dateOfHire,
        "sreet_address": sreetAddress,
        "sreet_city": sreetCity,
        "street_state": streetState,
        "street_postcode": streetPostcode,
        "street_country": streetCountry,
        "po_box_address": poBoxAddress,
        "po_box_city": poBoxCity,
        "po_box_state": poBoxState,
        "po_box_postcode": poBoxPostcode,
        "po_box_country": poBoxCountry,
        "home_phone": homePhone,
        "cell_phone": cellPhone,
        "contact_name": contactName,
        "contact_number": contactNumber,
        "medical_conditions_note": medicalConditionsNote,
        "regular_medications": regularMedications,
        "home_phone_no": homePhoneNo,
        "cell_phone_no": cellPhoneNo,
        "emergency_email": emergencyEmail,
        "skills": skills,
        "skill_lock": skillLock,
        "employee_status_id": employeeStatusId,
        "vacation_start": vacationStart,
        "vacation_end": vacationEnd,
        "image": image,
        "available_times": availableTimes,
        "seniority": seniority,
        "custom_field1": customField1,
        "custom_field2": customField2,
      };
}
